fixture_user = [{"username": "Semenov",
            "first_name": "Семен",
            "last_name": "Семенов",
            "email": "sema.ik1987@yandex.ru",
            "password": "123456lkldfkdfs"},

           {"username": "Semen",
            "first_name": "Семен",
            "last_name": "Иванов",
            "email": "ivanov19@yandex.ru",
            "password": "123456lkldfkdfs"},

            {"username": "Mihail",
            "first_name": "Миша",
            "last_name": "Михайлов",
            "email": "Misha2034@ya.ru",
            "password": "123456lkldfkdfs"},

           {"username": "Lexus",
            "first_name": "Алексей",
            "last_name": "Алексеев",
            "email": "lexmail@mail.ru",
            "password": "22fgffgldfkdfs"},

            {"username": "Vlad",
            "first_name": "Владислав",
            "last_name": "Владиславов",
            "email": "vladmen22@rambler.ru",
            "password": "56lkld45!!!!fkdfs"},

           {"username": "Yevgen",
            "first_name": "Евгений",
            "last_name": "Евгеньев",
            "email": "yevgen23@yahuu.ru",
            "password": "9256lkld!!fkdfs"},

            {"username": "Ural",
            "first_name": "Урал",
            "last_name": "Уралович",
            "email": "ural.mk22@yandex.ru",
            "password": "!%^gfh111s"},

           {"username": "Dima",
            "first_name": "Дмитрий",
            "last_name": "Дмитриев",
            "email": "dimamail@mail.ru",
            "password": "89!@112fkdfs"}]

fixture_contact = [
            {"city": "Москва",
              "street": "Ленина",
              "house": "11",
              "structure": "б",
              "building": "22",
              "apartment": "67",
              "phone": "8-951-325-33-22"},

            {"city": "Курск",
             "street": "Семенова",
             "house": "12",
             "structure": "а",
             "building": "23",
             "apartment": "12",
             "phone": "8-951-443-33-22"},

            {"city": "Хабаровск",
             "street": "Доватора",
             "house": "15",
             "structure": "с",
             "building": "1",
             "apartment": "17",
             "phone": "8-922-444-33-22"},

            {"city": "Самара",
             "street": "Кирова",
             "house": "12",
             "structure": "а",
             "building": "1",
             "apartment": "17",
             "phone": "8-922-114-33-22"},

            {"city": "Миасс",
             "street": "Навального",
             "house": "12",
             "structure": "б",
             "building": "2",
             "apartment": "6",
             "phone": "8-955-123-33-22"},

            {"city": "Тольяти",
             "street": "Михалкова",
             "house": "12",
             "structure": "х",
             "building": "12",
             "apartment": "11",
             "phone": "8-951-423-35-22"},

            {"city": "Новокузнецк",
             "street": "Шарапова",
             "house": "955",
             "structure": "п",
             "building": "1",
             "apartment": "27",
             "phone": "8-951-123-33-22"},

            {"city": "Златоуст",
             "street": "Симонова",
             "house": "45",
             "structure": "а",
             "building": "12",
             "apartment": "33",
             "phone": "8-912-456-12-33"},

]

fixture_shop = [
            {"name": "Связной",
            "url": "https://raw.githubusercontent.com/StanislavGrekov/my_diplom_drf/master/shop1.yaml"},
]