# примеры API-запросов

@baseUrl = http://localhost:8000/api/

####################### Работа с пользователем #################
###
# Запрос№2. на получение информации о пользователе
GET {{baseUrl}}user/detail/1/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

###
# Запрос№3. на создание пользователя
POST {{baseUrl}}user/create/
Content-Type: application/json

{
  "username": "Stas",
  "first_name": "Станислав",
  "last_name": "Греков",
  "email": "stas.ik1987@yandex.ru",
  "password": "123456"
}

###
# Запрос№4. на изменение пользователя
PATCH {{baseUrl}}user/update/1/
Content-Type: application/json
Authorization: Token b7d800d27c260dfb49523252ba910fa116d08f80

{
  "password": "123"
}

###

# Запрос№5. на удаление пользователя
DELETE {{baseUrl}}user/delete/1/
Content-Type: application/json
Authorization: Token a97708e55f33125be3c8b0ae9046e2f67367ef03


####################### Работа с контактом #################
###
# Запрос№6 Создание контакта
POST {{baseUrl}}contact/create/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

{
  "city": "Миасс",
  "street": "Седова",
  "house": "5",
  "structure": "а",
  "building": "1",
  "apartment": "67",
  "phone": "123456"
}

###

# Запрос№. На изменение контакта
PATCH {{baseUrl}}contact/update/1/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

{
  "city": "Кайгородово"
}


################# Запросы на создание и удаление магазина #################
###
# Запрос№6. Запрос на создание магазина и загрузку товара из прайса по указанному URL
POST {{baseUrl}}shop/create/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

{
  "name": "Связной",
  "url": "https://raw.githubusercontent.com/StanislavGrekov/my_diplom_drf/master/shop1.yaml"
}

###
# Запрос№. Запрос на получение списка магазинов
GET {{baseUrl}}shop/all/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

###
# Запрос№. На деактивацию магазина
PATCH {{baseUrl}}shop/update/3/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

{
  "state": "False"
}

###
# Запрос№7. Запрос на удаление магазина и товаров из прайса
DELETE {{baseUrl}}shop/delete/2/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15
###


############### Запросы на получение товара ##############

# Запрос№. на получение списка товаров (все товары)
GET {{baseUrl}}product/list/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

###
# Запрос№. Фильтрация по модели (вхождение текста)
GET {{baseUrl}}product/list/?search=xs-max
Content-Type: application/json
Authorization: Token 59876bf383edd0a8671100644100eaea5c39909f

###
# Запрос№. Фильтрация по стоимости (вхождение текста)
GET {{baseUrl}}product/list/?search=1300
Content-Type: application/json
Authorization: Token 61f7bf616051bcedb460c0e0805ae1d438245159

###
# Запрос№. Фильтрация по дате
GET {{baseUrl}}product/list/date/?time_create_after=2023-06-15&&time_create_before=2023-06-16
Content-Type: application/json
Authorization: Token 5d71e977a8e865247756bfa91f6790f2627dee66

###
# Запрос№. Фильтрация по категориям (вхождение текста)
GET {{baseUrl}}category/list/?search=Аксессуары
Content-Type: application/json
Authorization: Token 61f7bf616051bcedb460c0e0805ae1d438245159

###
# Запрос№. Фильтрация по магазинам (вхождение текста)
GET {{baseUrl}}shop/list/?search=Связной
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15


############### Работа с заказами ##############
###
# Запрос№. Просмотр корзины
GET {{baseUrl}}basket/list/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15


###
# Запрос№6 Создание заказа
POST {{baseUrl}}basket/add/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15

{ "shop":"Связной",
  "external_id":"4216292",
  "quantity": "3"
}

###
# Запрос№6 Удаление заказа
DELETE {{baseUrl}}basket/delete/15/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15




