# примеры API-запросов

@baseUrl = http://localhost:8000/api/

####################### Работа с пользователем #################
###

# Запрос№1. Создание пользователя
POST {{baseUrl}}usercreate/
Content-Type: application/json

{
  "username": "Sem",
  "first_name": "Семен",
  "last_name": "Семенов",
  "email": "stas.ik1987@yandex.ru",
  "password": "123456lkldfkdfs"
}


###

# Запрос№2. Получение информации о пользователе
GET {{baseUrl}}user/
Content-Type: application/json
Authorization: Token e08f62ab2c68555d0b7892167c237aeeb808cdc2

###
# Запрос№3. Изменение пользователя
PATCH {{baseUrl}}user/3/
Content-Type: application/json
Authorization: Token e08f62ab2c68555d0b7892167c237aeeb808cdc2

{
  "password": "123"
}

###
# Запрос№4. Удаление пользователя
DELETE {{baseUrl}}user/3/
Content-Type: application/json
Authorization: Token 1811c088fe042fdadecabd43b70750e9be0668ef


####################### Работа с контактом #################
###
# Запрос№5. Создание контакта
POST {{baseUrl}}contact/create/
Content-Type: application/json
Authorization: Token 32f61c8baffc911071f645ee58be24dbfa84f6db

{
  "city": "Челябинск",
  "street": "Благих",
  "house": "11",
  "structure": "а",
  "building": "1",
  "apartment": "67",
  "phone": "8-951-444-33-22"
}

###

# Запрос№6. Изменение контакта
PATCH {{baseUrl}}contact/update/1/
Content-Type: application/json
Authorization: Token 384d1f863e0945fc0c114c581fa9e6ebe17de222

{
  "city": "Кайгородово"
}


################# Запросы на создание и удаление магазина #################
###
# Запрос№7. Запрос на создание магазина и загрузку товара из прайса по указанному URL
POST {{baseUrl}}shop/create/
Content-Type: application/json
Authorization: Token 32f61c8baffc911071f645ee58be24dbfa84f6db

{
  "name": "Связной",
  "url": "https://raw.githubusercontent.com/StanislavGrekov/my_diplom_drf/master/shop1.yaml"
}

###
# Запрос№8. Запрос на получение списка магазинов
GET {{baseUrl}}shop/all/
Content-Type: application/json
Authorization: Token 32f61c8baffc911071f645ee58be24dbfa84f6db

###
# Запрос№9. На деактивацию магазина
PATCH {{baseUrl}}shop/update/1/
Content-Type: application/json
Authorization: Token 0e42ec1aa29a7729b79500bd3695d010a71d159f

{
  "state": "False"
}

###
# Запрос№10. Запрос на удаление магазина и товаров из прайса
DELETE {{baseUrl}}shop/delete/2/
Content-Type: application/json
Authorization: Token 07a9964a2ead74c2f0a3dddf2c2bce6100272d15
###


############### Запросы на получение товара ##############

# Запрос№11-1. Получение списка товаров (все товары)
GET {{baseUrl}}product/list/
Content-Type: application/json
Authorization: Token 32f61c8baffc911071f645ee58be24dbfa84f6db

###
# Запрос№11-2. Фильтрация по модели (вхождение текста)
GET {{baseUrl}}product/list/?search=xs-max
Content-Type: application/json
Authorization: Token 32f61c8baffc911071f645ee58be24dbfa84f6db

###
# Запрос№11-3. Фильтрация по стоимости (вхождение текста)
GET {{baseUrl}}product/list/?search=1300
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514

###
# Запрос№11-4. Фильтрация по дате
GET {{baseUrl}}product/list/date/?time_create_after=2023-06-15&&time_create_before=2023-06-16
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514

###
# Запрос№11-5. Фильтрация по категориям (вхождение текста)
GET {{baseUrl}}category/list/?search=Аксессуары
Content-Type: application/json
Authorization: Token 32f61c8baffc911071f645ee58be24dbfa84f6db

###
# Запрос№11-6. Фильтрация по магазинам (вхождение текста)
GET {{baseUrl}}shop/list/?search=Связной
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514


############### Работа с заказами ##############
###
# Запрос№12. Просмотр корзины
GET {{baseUrl}}basket/list/
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514

###
# Запрос№13 Создание заказа
POST {{baseUrl}}basket/add/
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514

{ "shop":"Связной",
  "external_id":"4672456",
  "quantity": "1"
}

###
# Запрос№14 Удаление заказа
DELETE {{baseUrl}}basket/delete/4/
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514
###

############### Обработка заказа ##############

# Запрос№15 Запрос для пользователя. Подразумевается, что пользователь, после того как добавил товары в корзину
# может подтвердить заказ ("state":"Confirmed"), а после получения заказа установить статус доставлено ("state":"Delivered")
# Выполняется сразу для всех заказов.
POST {{baseUrl}}order/processing/
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514

{ 
  "state":"Confirmed"
}

###
# Запрос№16. Запрос для пользователя. Просмотр статуса заказа
GET {{baseUrl}}order/list/
Content-Type: application/json
Authorization: Token 1bff16187689c5f66495b892330aaaf07c0a4514


###
# Запрос№17. Запрос для администратора. Просмотр заказа по номеру
GET {{baseUrl}}order/admin/list/15/
Content-Type: application/json
Authorization: Token 09d09282f47b580d13987a24dc28a61102c4b439

###
# Запрос№18 Запрос для администратора. Подразумевается, что администратор, после того как посмотрел заказ
#отправляет их в доставку
POST {{baseUrl}}order/admin/processing/
Content-Type: application/json
Authorization: Token 09d09282f47b580d13987a24dc28a61102c4b439

{ 
  "order":"3"
}
###


